### ISSUE TITLE
Speed of morphing operation

### ISSUE THREAD

**Issue by kwea123** [TWJianNuo/EdgeDepth-Release#3]
What is the runtime overhead introduced by morphing? Using cuda makes it run faster, so what's the speed in the actual implementation?

**Comment by TWJianNuo** [comment]
The algorithmn has a linear time complexity. I tested with a RTX 2080Ti Gpu, average time consumption is 0.14s for a 320 by 1024 size image, including all steps from distilling egdes, finding correspondence and morphing.
